--- #YAML:1.0
name:               Sys-Facter
version:            1.01
abstract:           ~
author:
    - Stanislaw Klekot <cpan@jarowit.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:  0
    Pfacter:       0
    POSIX:         0
    YAML:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
